const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Tilemap,
		C3.Plugins.Sprite,
		C3.Behaviors.Anchor,
		C3.Behaviors.solid,
		C3.Behaviors.Pin,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.bound,
		C3.Plugins.Keyboard,
		C3.Plugins.Audio,
		C3.Plugins.Button,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.JavaScriptInEvents.FolhaDeEventos1_Event18_Act3,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Button.Cnds.OnClicked
	];
};
self.C3_JsPropNameTable = [
	{pisoPorto: 0},
	{Âncora: 0},
	{planodefundo: 0},
	{Solid: 0},
	{agua: 0},
	{caixaVerde: 0},
	{caixaVermelha: 0},
	{caixaAmarela: 0},
	{caixaCinza: 0},
	{guindaste: 0},
	{garraguindaste: 0},
	{Vermelhaaberta: 0},
	{CaixaPreta: 0},
	{carrinho: 0},
	{cerquinha: 0},
	{caixa1: 0},
	{caixa2: 0},
	{caixa3: 0},
	{jaPintado: 0},
	{containergrafitti: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sólido: 0},
	{caixasolida: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{Sprite9: 0},
	{Sprite10: 0},
	{Sprite11: 0},
	{Sprite12: 0},
	{Sprite13: 0},
	{Sprite14: 0},
	{Fixar: 0},
	{Personagem_animacao: 0},
	{Plataforma: 0},
	{CentrarEm: 0},
	{RestritoAoLayout: 0},
	{Personagem_sensor: 0},
	{Teclado: 0},
	{graffiti1: 0},
	{Áudio: 0},
	{Platform: 0},
	{colisaoagua: 0},
	{Sprite: 0},
	{btn_start: 0},
	{Anchor: 0},
	{txt_vidas: 0},
	{imagemgameover: 0},
	{btn_jogardnv: 0},
	{imgfinal: 0},
	{btn_jogarnovamente: 0},
	{Sprite15: 0},
	{npc: 0},
	{balao_fala: 0},
	{npc2: 0},
	{balao_fala2: 0},
	{VIDAS: 0},
	{ContainersPintados: 0}
];

self.InstanceType = {
	pisoPorto: class extends self.ITilemapInstance {},
	planodefundo: class extends self.ISpriteInstance {},
	agua: class extends self.ITilemapInstance {},
	caixaVerde: class extends self.ISpriteInstance {},
	caixaVermelha: class extends self.ISpriteInstance {},
	caixaAmarela: class extends self.ISpriteInstance {},
	caixaCinza: class extends self.ISpriteInstance {},
	guindaste: class extends self.ISpriteInstance {},
	garraguindaste: class extends self.ISpriteInstance {},
	Vermelhaaberta: class extends self.ISpriteInstance {},
	CaixaPreta: class extends self.ISpriteInstance {},
	carrinho: class extends self.ISpriteInstance {},
	cerquinha: class extends self.ISpriteInstance {},
	caixa1: class extends self.ISpriteInstance {},
	caixa2: class extends self.ISpriteInstance {},
	caixa3: class extends self.ISpriteInstance {},
	containergrafitti: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	caixasolida: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	Sprite9: class extends self.ISpriteInstance {},
	Sprite10: class extends self.ISpriteInstance {},
	Sprite11: class extends self.ISpriteInstance {},
	Sprite12: class extends self.ISpriteInstance {},
	Sprite13: class extends self.ISpriteInstance {},
	Sprite14: class extends self.ISpriteInstance {},
	Personagem_animacao: class extends self.ISpriteInstance {},
	Personagem_sensor: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	graffiti1: class extends self.ISpriteInstance {},
	Áudio: class extends self.IInstance {},
	colisaoagua: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	btn_start: class extends self.IButtonInstance {},
	txt_vidas: class extends self.ITextInstance {},
	imagemgameover: class extends self.ISpriteInstance {},
	btn_jogardnv: class extends self.IButtonInstance {},
	imgfinal: class extends self.ISpriteInstance {},
	btn_jogarnovamente: class extends self.IButtonInstance {},
	Sprite15: class extends self.ISpriteInstance {},
	npc: class extends self.ISpriteInstance {},
	balao_fala: class extends self.ITextInstance {},
	npc2: class extends self.ISpriteInstance {},
	balao_fala2: class extends self.ITextInstance {}
}